replicaCount: 1

# image: chethanuk/polynote:0.3.12-py38-spark
# image: chethanuk/polynote:0.3.12-py38-sparkhd3
image:
  repository: chethanuk/polynote
  pullPolicy: Always
  tag: "0.3.12-spark3hd3-py38-su" # 0.3.12-spark3hd3-py38

config:
  path: "/opt/config/prodconfig.yml"

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. uncomment the following lines, adjust them as necessary, 
  # and remove the curly braces after 'resources:'.
  requests:
    cpu: 10000m
    memory: 25Gi
#  limits:
#    cpu: 10000m
#    memory: 25Gi

service:
  spark:
    enabled: true

sync:
  enabled: true
  rclone:
    sleep: 30
    gcs:
      bucket: "pr-6853a6c6-bucket"
      saSecretName: "gcp-sa-account"
    image:
      tag: 1.5.4-code
      pullPolicy: Always

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: component
          operator: In
          values:
          - jupyter
